### PR TITLE
Update vcpkg version to 27fd32e91c172e8b8a2ee338efc088a0c0103348 and add assimp and graphviz

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/917 .
Fix https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/issues/18 .

### CODE REVIEW

**Comment by traversaro** [comment]
pcre2 network failure:
~~~
2021-11-07T20:11:16.2681397Z Starting package 27/42: pcre2:x64-windows
2021-11-07T20:11:16.2682195Z Building package pcre2[core]:x64-windows...
2021-11-07T20:11:38.3569810Z CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:77 (message):
2021-11-07T20:11:38.3666135Z   SILENT_EXIT has been deprecated as an argument to vcpkg_download_distfile
2021-11-07T20:11:38.3667752Z   -- remove the argument to resolve this warning
2021-11-07T20:11:38.3668482Z Call Stack (most recent call first):
2021-11-07T20:11:38.3669298Z   ports/pcre2/portfile.cmake:7 (vcpkg_download_distfile)
2021-11-07T20:11:38.3670088Z   scripts/ports.cmake:141 (include)
2021-11-07T20:11:38.3670538Z 
2021-11-07T20:11:38.3670873Z 
2021-11-07T20:11:38.3671703Z -- Downloading https://ftp.pcre.org/pub/pcre/pcre2-10.37.zip -> pcre2-10.37.zip...
2021-11-07T20:11:38.3672741Z [DEBUG] Feature flag 'binarycaching' unset
2021-11-07T20:11:38.3673464Z [DEBUG] Feature flag 'manifests' = off
2021-11-07T20:11:38.3674158Z [DEBUG] Feature flag 'compilertracking' unset
2021-11-07T20:11:38.3674921Z [DEBUG] Feature flag 'registries' unset
2021-11-07T20:11:38.3675872Z [DEBUG] Feature flag 'versions' unset
2021-11-07T20:11:38.3677376Z [DEBUG] Downloading https://ftp.pcre.org/pub/pcre/pcre2-10.37.zip
2021-11-07T20:11:38.3678478Z Error: Failed to download from mirror set:
2021-11-07T20:11:38.3679712Z https://ftp.pcre.org/pub/pcre/pcre2-10.37.zip: WinHttpSendRequest() failed: 12002
2021-11-07T20:11:38.3680766Z 
2021-11-07T20:11:38.3681648Z [DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
2021-11-07T20:11:38.3682191Z [DEBUG] Exiting after 21052315 us (21041488 us)
2021-11-07T20:11:38.3682506Z 
2021-11-07T20:11:38.3683093Z CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:251 (message):
2021-11-07T20:11:38.3683714Z       
2021-11-07T20:11:38.3684132Z       Failed to download file.
2021-11-07T20:11:38.3684789Z       If you use a proxy, please check your proxy setting. Possible causes are:
2021-11-07T20:11:38.3686062Z       
2021-11-07T20:11:38.3686710Z       1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
2021-11-07T20:11:38.3687869Z          to `https://address:port`. This is not correct, because `https://` prefix
2021-11-07T20:11:38.3689002Z          claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
2021-11-07T20:11:38.3689986Z          , etc..) is an HTTP proxy. Try setting `http://address:port` to both
2021-11-07T20:11:38.3690827Z          HTTP_PROXY and HTTPS_PROXY instead.
2021-11-07T20:11:38.3691356Z       
2021-11-07T20:11:38.3692164Z       2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
2021-11-07T20:11:38.3693757Z          will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
2021-11-07T20:11:38.3694986Z          Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
2021-11-07T20:11:38.3696058Z          Change `http=address:port;https=address:port` to `address`, and fill the port number.
2021-11-07T20:11:38.3696855Z       
2021-11-07T20:11:38.3698026Z       3. You proxy's remote server is out of service.
2021-11-07T20:11:38.3698624Z       
2021-11-07T20:11:38.3699276Z       In future vcpkg releases, if you are using Windows, you no longer need to set
2021-11-07T20:11:38.3700259Z       HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
2021-11-07T20:11:38.3701370Z       Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
2021-11-07T20:11:38.3702360Z       and (https://github.com/microsoft/vcpkg-tool/pull/77)
2021-11-07T20:11:38.3703057Z       
2021-11-07T20:11:38.3703832Z       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
2021-11-07T20:11:38.3704467Z 
2021-11-07T20:11:38.3704982Z Call Stack (most recent call first):
2021-11-07T20:11:38.3705758Z   ports/pcre2/portfile.cmake:7 (vcpkg_download_distfile)
2021-11-07T20:11:38.3706533Z   scripts/ports.cmake:141 (include)
2021-11-07T20:11:38.3706969Z 
2021-11-07T20:11:38.3707346Z 
2021-11-07T20:11:38.3707986Z Error: Building package pcre2:x64-windows failed with: BUILD_FAILED
2021-11-07T20:11:38.3708914Z Please ensure you're using the latest portfiles with `.\vcpkg update`, then
2021-11-07T20:11:38.3709890Z submit an issue at https://github.com/Microsoft/vcpkg/issues including:
2021-11-07T20:11:38.3711039Z   Package: pcre2:x64-windows
2021-11-07T20:11:38.3711878Z   Vcpkg version: 2021-07-21-244f69e78da4f97034328b4d290db262d748d4c7
2021-11-07T20:11:38.3712438Z 
2021-11-07T20:11:38.3713147Z Additionally, attach any relevant sections from the log files above.
2021-11-07T20:11:38.4023535Z ##[error]Process completed with exit code 1.
2021-11-07T20:11:38.4980005Z Cleaning up orphan processes
~~~

**Comment by traversaro** [comment]
> 
> 
> Upstream issue: [microsoft/vcpkg#21201](https://github.com/microsoft/vcpkg/issues/21201) .

The tricky thing here is that even if they fix the issue in the latest vcpkg, either we need to update to the latest vcpkg, or keep our own fork. This is due to vcpkg reliance on upstream tarballs.

**Comment by traversaro** [comment]
> > Upstream issue: [microsoft/vcpkg#21201](https://github.com/microsoft/vcpkg/issues/21201) .
> 
> The tricky thing here is that even if they fix the issue in the latest vcpkg, either we need to update to the latest vcpkg, or keep our own fork. This is due to vcpkg reliance on upstream tarballs.

At this point, let's update so we can get also graphviz, see https://github.com/robotology/robotology-superbuild/pull/988 .

**Comment by traversaro** [comment]
CI fails with:
~~~
-- Installing: C:/robotology/vcpkg/packages/ace_x64-windows/include/ace/os_include/sys/os_utsname.h
-- Installing: C:/robotology/vcpkg/packages/ace_x64-windows/include/ace/os_include/sys/os_wait.h
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(656)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 6 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2427 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 26.75 s (26739454 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. You proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:84 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:174 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_find_acquire_program.cmake:547 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/ace/portfile.cmake:431 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)


Error: Building package ace:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ace
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ace]+Build+error
including:
  package: ace[core]:x64-windows -> 7.0.5#1
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (4 months ago)

Additionally, attach any relevant sections from the log files above.
Error: Process completed with exit code 1.
~~~

**Comment by traversaro** [comment]
(I killed the push CI to avoid cross-talking with the pull request one)

**Comment by traversaro** [comment]
> Perhaps we should first zip the directory on our own, and then upload it to artifacts once zipped.

For now in https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/commit/d09ed2504902128719530bf624b79971309a99e2 I tried to update the versions of the upload and download artifacts.

**Comment by traversaro** [comment]
> > Perhaps we should first zip the directory on our own, and then upload it to artifacts once zipped.
> 
> For now in [d09ed25](https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/commit/d09ed2504902128719530bf624b79971309a99e2) I tried to update the versions of the upload and download artifacts.

Now we have again the msys2 problem, bumped vcpkg to 27fd32e91c172e8b8a2ee338efc088a0c0103348 (latest master) to try to solve it.

**Comment by pattacini** [comment]
Failed again 😞
This time because of `libxml2[core]`: same as always, unreachable mirror.
And we were using the latest vcpkg, if I'm not mistaken.

**Comment by traversaro** [comment]
Now `build-with-gazebo-deps` step was successful, while `build-with-gazebo` failed with a problem similar to the one that we had before for `build-with-gazebo-deps`.

**Comment by traversaro** [comment]
> Now `build-with-gazebo-deps` step was successful, while `build-with-gazebo` failed with a problem similar to the one that we had before for `build-with-gazebo-deps`.

To solve once and for all these kind of problems, I swithced to pre-compress all the artifacts, fixing https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/issues/18 .

**Pull request merged**
