### PR TITLE
Add glew, glfw3 and portaudio dependencies

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/issues/22
Fix https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/issues/15

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Should we change also the Readme for the manual installation?

**Comment by traversaro** [comment]
> 
> 
> Should we change also the Readme for the manual installation?

Which README? robotology-superbuild?

**Comment by S-Dafarra** [comment]
> > 
> > 
> > Should we change also the Readme for the manual installation?
> 
> Which README? robotology-superbuild? 

Yes I was referring to https://github.com/robotology/robotology-superbuild/blob/master/doc/vcpkg-dependencies.md . I have seen later that it is on the superbuild.

**Comment by traversaro** [comment]
> 
> 
> > > Should we change also the Readme for the manual installation?
> > 
> > 
> > Which README? robotology-superbuild?
> 
> Yes I was referring to https://github.com/robotology/robotology-superbuild/blob/master/doc/vcpkg-dependencies.md . I have seen later that it is on the superbuild.

Done in https://github.com/robotology/robotology-superbuild/pull/431 .

**Pull request merged**
